### ISSUE TITLE
Changing server attributes doesn't update server IP in the client config

### ISSUE THREAD

**Issue by ocervell** [forseti-security/terraform-google-forseti#129]
When modifying something on the server VM (such as the server region) - this triggers delete / create of the server VM but doesn't change the `server_ip` in the client config. This makes the client time out when running Forseti command as it's trying to contact the old server IP.

**Comment by mogthesprog** [comment]
Yep, it looks like you have to run apply twice.

One way to fix this is to support providing a static server IP, which you can provision outside the module and pass in. That way the config and the server know what the server IP is every time.

**Comment by gkowalski-google** [comment]
@ocervell @mogthesprog I accidentally created a [duplicate issue](https://github.com/forseti-security/terraform-google-forseti/issues/295) of this. Instead of creating a static IP, I found that we can use the internal DNS of the GCE instance. Does that solution look good? If so, then I will close this out and we will try to get this fixed with the next release.

**Comment by gkowalski-google** [comment]
Will be resolved in #295.
