### ISSUE TITLE
Error granting roles on tf helper

### ISSUE THREAD

**Issue by menendezjaume** [forseti-security/terraform-google-forseti#23]
The tf helper doesn't grant the appropriate roles in the following sections:

https://github.com/terraform-google-modules/terraform-google-forseti/blob/b7f70a6b63a894ea60ab73834e8b02ed58b260c0/helpers/forseti-setup.tf#L48-L52

https://github.com/terraform-google-modules/terraform-google-forseti/blob/b7f70a6b63a894ea60ab73834e8b02ed58b260c0/helpers/forseti-setup.tf#L54-L58

**Comment by adrienthebo** [comment]
We dropped the `helpers/forseti-setup.tf` Terraform configuration in the v1.0 release of this module; in addition to the issues that you mentioned that configuration had bugs around managing IAM bindings vs members, and so on. Because of this we decided to drop this in favor of the `scripts/setup.sh`. Having a Terraform based setup configuration would be nicer than a shell script but we have no immediate plans to add that configuration.

If you'd be willing to add an updated version of the Terraform setup script we'd be happy to help out, just comment on this issue and we can continue this conversation.
