### ISSUE TITLE
Certain scanners does not have enable/disable flag.

### ISSUE THREAD

**Issue by xingao267** [forseti-security/terraform-google-forseti#511]
The following yamls/scanners that are included in the `modules/rules/templates/` seem does not have corresponding `_enable` attributes in the module so I can turn on and off the API calls.
```
external_project_access_rules.yaml
retention_rules.yaml
role_rules.yaml
```

**Comment by xingao267** [comment]
role scanner can be disabled since https://github.com/forseti-security/terraform-google-forseti/pull/526

**Comment by gkowalski-google** [comment]
Hi @xingao267, there is a ticket to enable/disable the retention scanner: https://github.com/forseti-security/terraform-google-forseti/issues/521.

The external project access scanner does not get run by the forseti scanner run command because it can take a very long time to complete. If you want to run this scanner, then it has to be run manually:
```
forseti scanner run --scanner external_project_access_scanner
```

Since we have a ticket for the retention scanner, are you ok with me closing this one?

**Comment by xingao267** [comment]
@gkowalski-google thanks for the explanation, sgtm.
