### ISSUE TITLE
Server VM startup script will always halt after restart/reset when internet connection is disallowed post installation.

### ISSUE THREAD

**Issue by xingao267** [forseti-security/terraform-google-forseti#547]
The current startup script uses `ping` to test internet connectivity and when the connectivity is `offline`, it will keep the `forseti-security/` folder at home directory. This will always cause the following command [here](https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl#L53) to fail to halt the startup script:

```
Mar 13 19:47:34 forseti-server-vm-{suffix} startup-script: INFO startup-script: Forseti Startup - Cloning Forseti repo.
Mar 13 19:47:34 forseti-server-vm-{suffix} startup-script: INFO startup-script: fatal: destination path 'forseti-security' already exists and is not an empty directory.
Mar 13 19:47:34 forseti-server-vm-{suffix} startup-script: INFO startup-script: Return code 128.
Mar 13 19:47:34 forseti-server-vm-{suffix} startup-script: INFO Finished running startup scripts.
```

A quick fix directly for this would be moving the `git clone` command to be in the `if` block as well when it is still `online`.

But I think this might be a broader issue for people who remove NAT after initial provisioning and restart VMs for various reasons (testing new rules/policies, debugging etc) as more command should be protected by this online or offline evaluation to be run or not.

We see this error happen because when we modify the policies in the server bucket, we want to test them right away, so we restart the VM, and that will rerun the startup script. But errors occur before we even hit the line that do gsutil to copy the policies from the bucket to the VM. Maybe that's a pattern we should tell users to avoid? And users shouldn't restart the VM afterwards, but restarting the VM seems a common use case.

**Comment by xingao267** [comment]
still seems to be an issue

**Comment by gkowalski-google** [comment]
@xingao267 Is this something you are still interested in? Since there are quite a few things in the startup script that require internet access, I'd rather not try to update it to have conditional logic everywhere. For your use case, maybe we can just add a helper script that you can run to pull the latest policies from GCS?

**Comment by vvdaal** [comment]
I've noticed the same problem when you run a proxy that only allows http/https as PING uses ICMP.
Suggestion, make a flag that is checked and will skip ping and basically forces the output to be ONLINE.

An environment value such as "FORCE_NO_CONN_CHECK" maybe?

In the file
```
https://github.com/forseti-security/terraform-google-forseti/blob/master/modules/server/templates/scripts/forseti-server/forseti_server_startup_script.sh.tpl
```

Maybe change ```INTERNET_CONNECTION="$(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline)"```

to

```
if [ $FORCE_NO_CONN_CHECK== "true" ]; then
   INTERNET_CONNECTION="online"
else
   INTERNET_CONNECTION="$(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline)"
fi
```

**Comment by gkowalski-google** [comment]
Thanks @vvdaal, that would ensure the check wouldn't false fail on the ping, but I think in order for this change to be successful, the startup script would need quite a few updates. Anything that is going out to the internet would still fail. If someone wants to modify try updating the startup script so that if the server does not have an internet connection, then it should not attempt the things that will fail and run only the commands that will help the server startup correctly.
